spring:
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 10000
      minimum-idle: 20
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 256MB
      max-request-size: 256MB
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher